export const gameLabels = {
	title: "Tales from the Loop",
	character: {
		general: {
			firstName: "Prénom",
			lastName: "Nom",
			age: "Âge",
			luck: "Chance",
			archetype: "Archétype",
			fetish: "Objet fétiche",
			favoriteSong: "Chanson préférée",
			problem: "Problème",
			drive: "Motivation",
			pride: "Fierté",
			socle: "Socle",
		},
		attributes: {
			body: "Physique",
			tech: "Technique",
			heart: "Cœur",
			mind: "Intelligence",
		},
		skills: {
			agility: "Agilité",
			strength: "Force",
			sneak: "Furtivité",
			analyze: "Analyse",
			tinker: "Bricolage",
			program: "Programmation",
			charisma: "Charisme",
			charm: "Charme",
			contact: "Réseau",
			comprehend: "Compréhension",
			discover: "Découverte",
			empathize: "Empathie",
		},
	},
};
